#!/bin/bash

[ ! -f "/etc/ssh/ssh_host_rsa_key" ] && dpkg-reconfigure openssh-server

mkdir -p /root/.ssh/
cp /authorized_keys /root/.ssh/
chmod 700 /root/.ssh
chmod 600 /root/.ssh/*

exec /usr/sbin/sshd -D -e
